name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
        with:
          python-version: 3.8

      - name: Build and publish
        env:
          PDM_PUBLISH_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: pdm publish
